# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name:  GitHub CICD

on:
  push:
    branches: [ master ]
    
env:
  GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
  MY_GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Re install dependencies
        run: gradle clean
      - name: Build bootWar
        run: gradle build
      - name: Build jar
        run: gradle bootJar
      - name: Deploy to gihub pages 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          token: ${{ secrets.GITHUBTOKEN }}
          branch: master # The branch the action should deploy to.
          repository-name: ospic/WJar
          folder: build/libs # The folder the action should deploy.
